name: ThePit
version: '${project.version}'
main: me.zelha.thepit.Main
api-version: 1.17
authors: [ hmzel ]
description: Recreation of Minikloon's The Pit
website: E
commands:
  setprestige:
    description: sets your or the specified player's prestige
    usage: /<command>
  setlevel:
    description: sets your or the specified player's level
    usage: /<command> (name/empty) (integer)
  setgold:
    description: sets your or the specified player's gold
    usage: /<command> (name/empty) (integer/double)
  setexp:
    description: sets your or the specified player's exp
    usage: /<command> (name/empty) (integer)
  setstatus:
    description: sets your or the specified player's status
    usage: /<command>
  setbounty:
    description: sets your or the specified player's bounty
    usage: /<command> (name/empty) (integer) (true/false/empty)
  setstreak:
    description: sets your or the specified player's streak
    usage: /<command>
  letmeplaceblocksplease:
    description: lets you place blocks because you asked nicely
    usage: /<command>
  respawn:
    description: sends you to spawn
    usage: /<command>
    aliases:
      - spawn
  setpassive:
    description: sets your or the specified player's passive
    usage: /<command> (name/empty) (passive) (integer)
  npccheck:
    description: spawns npcs if theyre absent
    usage: /<command>
  hologramcheck:
    description: spawns holograms if theyre absent
    usage: /<command>
  setperk:
    description: sets your or the specified player's perk at the given slot
    usage: /<command> (name/empty) (integer slot) (perk)
